package com.techplicit.mycarnival.utils;

/**
 * Created by pnaganjane001 on 17/12/15.
 */
public interface Constants {
    String ERROR = "ERROR";
    String SUCCESS = "SUCCESS";
    String NETWORK_FAIL = "NETWORK_FAIL";
    String STATUS = "Status";

    String POSITION = "POSITION";
    String BAND_NAME = "BAND_NAME";

    String SELECTED_CARNIVAL_NAME = "SELECTED_CARNIVAL_NAME";
    String SELECTED_BAND_NAME = "SELECTED_BAND_NAME";
    String SELECTED_BAND_ADDRESS = "SELECTED_BAND_ADDRESS";
    String SELECTED_BAND_LATITUDE = "SELECTED_BAND_LATITUDE";
    String SELECTED_BAND_LONGITUDE = "SELECTED_BAND_LONGITUDE";

    String UPDATE_LOCATION_FROM = "UPDATE_LOCATION_FROM";
    String FROM_BAND_UPDATE_BUTTON = "FROM_BAND_UPDATE_BUTTON";
    String FROM_BANDS_LIST = "FROM_BANDS_LIST";

    String PREFS_CARNIVAL = "PREFS_CARNIVAL";

    String IS_LOCATION_UPDATED = "IS_LOCATION_UPDATED";

    String IS_DISATNCE_NEEDS_TO_LOAD = "IS_DISATNCE_NEEDS_TO_LOAD";
    String IS_ALPH_SORT_NEEDS_TO_LOAD = "IS_ALPH_SORT_NEEDS_TO_LOAD";
    String IS_FAVS_NEEDS_TO_LOAD = "IS_FAVS_NEEDS_TO_LOAD";
    String IS_VIEW_NEEDS_TO_LOAD = "IS_VIEW_NEEDS_TO_LOAD";

    String IS_GPS_DIALOG_SHOWING = "IS_GPS_DIALOG_SHOWING";

    String BASE_URL = "http://52.89.123.186/carnival/service/";
}
